### ISSUE TITLE
V3 not found ? wrong documentation 

### ISSUE THREAD

**Issue by golliholzland** [basecom/FixturesPlugin#66]
Hi, 
the documentation for this plugin mentions support of SW 6.6* with v3.0. but this version is not available, last version was v2.4.
any plans to release v3.0 ?

**Comment by rvalley98** [comment]
Hey, the release of version 3.0 is planned for this week.

**Comment by jkniest** [comment]
Good morning! FYI we are releasing the V3 today (only finishing up the documentation and upgrade guide). I'll let you know in this issue

**Comment by jkniest** [comment]
@golliholzland Version 3 is now released 🥳 

Please note that this release has a few breaking changes. See our upgrade guide for this: https://basecom.github.io/FixturesPlugin/upgrade.html
